- fileioapp/src/main/java/ch/heig/dai/lab/fileio/ChristopheKunzli/EncodingSelector.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/ChristopheKunzli/FileExplorer.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/ChristopheKunzli/FileReaderWriter.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/ChristopheKunzli/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/ChristopheKunzli/EncodingSelectorTest.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/ChristopheKunzli/FileExplorerTests.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/ChristopheKunzli/TransformerTest.java
> Create folders for ChristopheKunzli

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/aleddaheig/EncodingSelector.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/aleddaheig/FileExplorer.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/aleddaheig/FileReaderWriter.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/aleddaheig/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/aleddaheig/EncodingSelectorTest.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/aleddaheig/FileExplorerTests.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/aleddaheig/TransformerTest.java
> Create folders for aleddaheig

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/CestPolo/EncodingSelector.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/CestPolo/FileExplorer.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/CestPolo/FileReaderWriter.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/CestPolo/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/cestpolo/EncodingSelectorTest.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/cestpolo/FileExplorerTests.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/cestpolo/TransformerTest.java
> Create folders for CestPolo

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/JeffMv/EncodingSelector.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/JeffMv/FileExplorer.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/JeffMv/FileReaderWriter.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/JeffMv/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/JeffMv/EncodingSelectorTest.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/JeffMv/FileExplorerTests.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/JeffMv/TransformerTest.java
> Create folders for JeffMv

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/elchami21/EncodingSelector.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/elchami21/FileExplorer.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/elchami21/FileReaderWriter.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/elchami21/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/elchami21/EncodingSelectorTest.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/elchami21/FileExplorerTests.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/elchami21/TransformerTest.java
> Feature create folders

- fileioapp/axelrochat/main/EncodingSelector.java
- fileioapp/axelrochat/main/FileExplorer.java
- fileioapp/axelrochat/main/FileReaderWriter.java
- fileioapp/axelrochat/main/Transformer.java
- fileioapp/axelrochat/test/EncodingSelectorTest.java
- fileioapp/axelrochat/test/FileExplorerTests.java
- fileioapp/axelrochat/test/TransformerTest.java
> Create folder for AxelRochat

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/VinchXVI/EncodingSelector.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/VinchXVI/FileExplorer.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/VinchXVI/FileReaderWriter.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/VinchXVI/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/VinchXVI/EncodingSelectorTest.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/VinchXVI/FileExplorerTests.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/VinchXVI/TransformerTest.java
> Create folders for VinchXVI

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/bvernet/EncodingSelector.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/bvernet/FileExplorer.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/bvernet/FileReaderWriter.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/bvernet/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/bvernet/EncodingSelectorTest.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/bvernet/FileExplorerTests.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/bvernet/TransformerTest.java
> Create folders for bvernet

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/rgborgeaud/EncodingSelector.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/rgborgeaud/FileExplorer.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/rgborgeaud/FileReaderWriter.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/rgborgeaud/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/rgborgeaud/EncodingSelectorTest.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/rgborgeaud/FileExplorerTests.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/rgborgeaud/TransformerTest.java
> Create folders for rgborgeaud

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/Nathanael_Delacrausaz/EncodingSelector.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/Nathanael_Delacrausaz/FileExplorer.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/Nathanael_Delacrausaz/FileReaderWriter.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/Nathanael_Delacrausaz/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/Nathanael_Delacrausaz/EncodingSelectorTest.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/Nathanael_Delacrausaz/FileExplorerTests.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/Nathanael_Delacrausaz/TransformerTest.java
> Create foolders for Nathanael-Delacrausaz

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/svelva/EncodingSelector.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/svelva/FileExplorer.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/svelva/FileReaderWriter.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/svelva/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/svelva/EncodingSelectorTest.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/svelva/FileExplorerTests.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/svelva/TransformerTest.java
> Create folders for Svelva

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/_9r55hs/EncodingSelector.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/_9r55hs/FileExplorer.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/_9r55hs/FileReaderWriter.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/_9r55hs/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/_9r55hs/EncodingSelectorTest.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/_9r55hs/FileExplorerTests.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/_9r55hs/TransformerTest.java
Create folders for 9r55hs.
Closes issue #1 
> **Note:** The folders are named '_9r55hs' to avoid problems in Java
> Create folders for 9r55hs

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/AnthonyChristen/EncodingSelector.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/AnthonyChristen/FileExplorer.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/AnthonyChristen/FileReaderWriter.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/AnthonyChristen/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/AnthonyChristen/EncodingSelectorTest.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/AnthonyChristen/FileExplorerTests.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/AnthonyChristen/TransformerTest.java
> Create folders for Anthony-Christen

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/Gabi3469/EncodingSelector.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/Gabi3469/FileExplorer.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/Gabi3469/FileReaderWriter.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/Gabi3469/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/Gabi3469/EncodingSelectorTest.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/Gabi3469/FileExplorerTests.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/Gabi3469/TransformerTest.java
> Create folders for Gabi3469

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/ryadbouzourene/EncodingSelector.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/ryadbouzourene/FileExplorer.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/ryadbouzourene/FileReaderWriter.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/ryadbouzourene/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/ryadbouzourene/EncodingSelectorTest.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/ryadbouzourene/FileExplorerTests.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/ryadbouzourene/TransformerTest.java
> Create folders for ryadbouzourene

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/LovIMarK/EncodingSelector.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/LovIMarK/FileExplorer.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/LovIMarK/FileReaderWriter.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/LovIMarK/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/LovIMarK/EncodingSelectorTest.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/LovIMarK/FileExplorerTests.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/LovIMarK/TransformerTest.java
> Closes #84

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/IlianTopalov/EncodingSelector.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/IlianTopalov/FileExplorer.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/IlianTopalov/FileReaderWriter.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/IlianTopalov/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/IlianTopalov/EncodingSelectorTest.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/IlianTopalov/FileExplorerTests.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/IlianTopalov/TransformerTest.java
> Create folders for IlianTopalov

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/joelCarman/EncodingSelector.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/joelCarman/FileExplorer.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/joelCarman/FileReaderWriter.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/joelCarman/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/joelCarman/EncodingSelectorTest.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/joelCarman/FileExplorerTests.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/joelCarman/TransformerTest.java
> Create folders for joelCarman

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/CestPolo/EncodingSelector.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/CestPolo/FileExplorer.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/CestPolo/FileReaderWriter.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/CestPolo/Transformer.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/Main.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/cestpolo/EncodingSelectorTest.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/cestpolo/FileExplorerTests.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/cestpolo/TransformerTest.java
> FileExplorer implementation for CestPolo

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/FehlmannDy/EncodingSelector.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/FehlmannDy/FileExplorer.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/FehlmannDy/FileReaderWriter.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/FehlmannDy/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/FehlmannDy/EncodingSelectorTest.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/FehlmannDy/FileExplorerTests.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/FehlmannDy/TransformerTest.java
> Create folders for FehlmannDy

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/KurohanaNita/EncodingSelector.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/KurohanaNita/FileExplorer.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/KurohanaNita/FileReaderWriter.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/KurohanaNita/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/KurohanaNita/EncodingSelectorTest.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/KurohanaNita/FileExplorerTests.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/KurohanaNita/TransformerTest.java
> Create folders for KurohanaNita

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/hliosone/EncodingSelector.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/hliosone/FileExplorer.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/hliosone/FileReaderWriter.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/hliosone/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/hliosone/EncodingSelectorTest.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/hliosone/FileExplorerTests.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/hliosone/TransformerTest.java
> Create folder for hliosone

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/EscapedGibbon/EncodingSelector.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/EscapedGibbon/FileExplorer.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/EscapedGibbon/FileReaderWriter.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/EscapedGibbon/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/EscapedGibbon/EncodingSelectorTest.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/EscapedGibbon/FileExplorerTests.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/EscapedGibbon/TransformerTest.java
> Create folders for EscapedGibbon

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/aleddaheig/FileExplorer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/aleddaheig/FileExplorerTests.java
> FileExplorer aleddaheig

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/CestPolo/EncodingSelector.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/cestpolo/EncodingSelectorTest.java
> EncodingSelector implemented for CestPolo

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/JeffMv/FileExplorer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/JeffMv/FileExplorerTests.java
> FileExplorer JeffMv

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/elchami21/FileExplorer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/elchami21/FileExplorerTests.java
> Feature file_explorer

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/ChristopheKunzli/FileExplorer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/ChristopheKunzli/FileExplorerTests.java
> Feature FileExplorer for ChristopheKunzli

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/trigerber/FileExplorer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/trigerber/FileExplorerTests.java
> FileExplorer for trigerber

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/aleddaheig/EncodingSelector.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/aleddaheig/EncodingSelectorTest.java
> EncodingSelector aleddaheig

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/_9r55hs/FileExplorer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/_9r55hs/FileExplorerTests.java
Closes issue #95 
> **Note:** Folders are named _9r55hs to avoid problems with packages in Java
> FileExplorer 9r55hs

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/LovIMarK/FileExplorer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/LovIMarK/FileExplorerTests.java
> FileExplorer for LovIMarK

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/AnthonyChristen/FileExplorer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/AnthonyChristen/FileExplorerTests.java
> Implementation of FileExplorer for Anthony-Christen

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/ChristopheKunzli/EncodingSelector.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/ChristopheKunzli/EncodingSelectorTest.java
> feature EncodingSelector for ChristopheKunzli

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/rgborgeaud/FileExplorer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/rgborgeaud/FileExplorerTests.java
> FileExplorer rgborgeaud

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/joelCarman/FileExplorer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/joelCarman/FileExplorerTests.java
> FileExplorer for joelCarman

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/JeffMv/EncodingSelector.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/JeffMv/EncodingSelectorTest.java
> Feature encoding selector for JeffMv

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/bvernet/FileExplorer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/bvernet/FileExplorerTests.java
> Implement FileExplorer for bvernet

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/trigerber/EncodingSelector.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/trigerber/EncodingSelectorTest.java
> Encoding Selector for trigerber

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/Nathanael_Delacrausaz/EncodingSelector.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/Nathanael_Delacrausaz/EncodingSelectorTest.java
> EncodingSelector for Nathanael-Delacrausaz

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/VinchXVI/FileExplorer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/VinchXVI/FileExplorerTests.java
> feature FileExplorer test ok for VinchXVI

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/ChristopheKunzli/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/ChristopheKunzli/TransformerTest.java
> Transformer for ChristopheKunzli

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/trigerber/FileReaderWriter.java
> FileReaderWriter for TriGerber

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/LovIMarK/EncodingSelector.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/LovIMarK/EncodingSelectorTest.java
> EncodingSelector for LovIMarK

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/LovIMarK/FileReaderWriter.java
> FileReaderWriter for LovIMarK

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/trigerber/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/trigerber/TransformerTest.java
> Transformer for TriGerber

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/ChristopheKunzli/Transformer.java
Closes #183 
Cleaner replaceChuck method
> Improve Transformer for ChristopheKunzli

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/EscapedGibbon/FileExplorer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/EscapedGibbon/FileExplorerTests.java
> Adds file explorer for EscapedGibbon

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/EscapedGibbon/EncodingSelector.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/EscapedGibbon/EncodingSelectorTest.java
> Adds feature encodingSelector for EscapedGibbon

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/EscapedGibbon/FileReaderWriter.java
> Adds feature fileReaderWriter for EscapedGibbon

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/EscapedGibbon/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/EscapedGibbon/TransformerTest.java
> Adds feature transformer for EscapedGibbon

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/svelva/FileExplorer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/svelva/FileExplorerTests.java
> Implements fileExplorer class

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/svelva/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/svelva/TransformerTest.java
> Implements transformer

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/chomusukeworks/EncodingSelector.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/chomusukeworks/EncodingSelectorTest.java
> Implemented the encoding selector class for chomusuke-works

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/IlianTopalov/EncodingSelector.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/IlianTopalov/EncodingSelectorTest.java
> Add: Feature encoding selector

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/joelCarman/EncodingSelector.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/joelCarman/EncodingSelectorTest.java
> add EncodingSelector for JoelCarman

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/VinchXVI/EncodingSelector.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/VinchXVI/EncodingSelectorTest.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/cestpolo/EncodingSelectorTest.java
> feature EncodingSelector ok VinchXVI

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/Evan_Charles/FileExplorer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/Evan_Charles/FileExplorerTests.java
> Closes #96

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/joelCarman/FileReaderWriter.java
> add FileReaderWriter for JoelCarman

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/AnthonyChristen/EncodingSelector.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/AnthonyChristen/EncodingSelectorTest.java
> Implementation of EncodingSelector for Anthony-Christen

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/rgborgeaud/EncodingSelector.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/rgborgeaud/EncodingSelectorTest.java
> EncodingSelector for rgborgeaud

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/TheoPilet/EncodingSelector.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/TheoPilet/EncodingSelectorTest.java
> implement feature encodingSelector

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/CestPolo/FileReaderWriter.java
> FileReaderWriter implemented for CestPolo

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/JeffMv/FileReaderWriter.java
> Feature File reader and writer for JeffMv

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/Gabi3469/FileExplorer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/Gabi3469/FileExplorerTests.java
> Add Code FileExplorer for Gabi3469

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/ryadbouzourene/FileExplorer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/ryadbouzourene/FileExplorerTests.java
> FileExplorer test succeed

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/VinchXVI/FileReaderWriter.java
> feature FileReaderWriter added

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/axelrochat/FileExplorer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/axelrochat/FileExplorerTests.java
> FileExplorer Axel Rochat

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/LovIMarK/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/LovIMarK/TransformerTest.java
> Transformer for LovIMarK

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/JeffMv/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/JeffMv/TransformerTest.java
> Feature Transformer for JeffMv

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/Jerome_Riedo/EncodingSelector.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/Jerome_Riedo/EncodingSelectorTest.java
> EncodingSelector for Jerome-Riedo

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/Romain720/FileExplorer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/Romain720/FileExplorerTests.java
> FileExplorer

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/AnthonyChristen/FileReaderWriter.java
> Implementation of FileReaderWriter for Anthony-Christen

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/TheoPilet/FileReaderWriter.java
> implement FileReaderWriter

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/CestPolo/Transformer.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/Main.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/CestPolo/TransformerTest.java
> Feature transformer

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/wolffheig/FileReaderWriter.java
> FileReaderWriter for wolff-heig

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/chomusukeworks/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/chomusukeworks/TransformerTest.java
> Transformer for chomusuke-works

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/wolffheig/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/wolffheig/TransformerTest.java
> Transformer for wolff-heig

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/_9r55hs/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/_9r55hs/TransformerTest.java
Transformer 9r55hs
Closes #350 
> Note: The folders are named '_9r55hs' to avoid problems in Java
> Transformer 9r55hs

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/Jerome_Riedo/FileReaderWriter.java
> FileReaderWriter for Jerome-Riedo

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/Evan_Charles/FileReaderWriter.java
> Close #363

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/Evan_Charles/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/Evan_Charles/TransformerTest.java
> Close #367

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/AnthonyChristen/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/AnthonyChristen/TransformerTest.java
> Implementation of Transformer for Anthony-Christen

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/thomasVn/EncodingSelector.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/thomasVn/EncodingSelectorTest.java
> EncodingSelector

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/thomasVn/FileReaderWriter.java
> FileReaderWriter

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/leirth/FileExplorer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/leirth/FileExplorerTests.java
> Feature file explorer

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/JeffMv/FileExplorer.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/JeffMv/FileReaderWriter.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/Main.java
> Feature main for JeffMv

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/aminekhelfi/FileReaderWriter.java
> Closes #411

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/Gabi3469/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/Gabi3469/TransformerTest.java
> Add code Transformer for Gabi3469

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/Main.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/fehlmanndy/EncodingSelector.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/fehlmanndy/FileExplorer.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/fehlmanndy/FileReaderWriter.java
- fileioapp/src/main/java/ch/heig/dai/lab/fileio/fehlmanndy/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/fehlmanndy/EncodingSelectorTest.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/fehlmanndy/FileExplorerTests.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/fehlmanndy/TransformerTest.java
> Feature recreate folders

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/rgborgeaud/FileReaderWriter.java
> FileReaderWriter for rgborgeaud

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/hliosone/Transformer.java
Fixed an issue within the Transformer class
> Closes #451

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/rgborgeaud/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/rgborgeaud/TransformerTest.java
> Transformer for rgborgeaud

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/chomusukeworks/Transformer.java
Fixed a bug creating redundant lines at the end of the transformed output.
Closes #470
> Bugfix transformer

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/ryadbouzourene/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/ryadbouzourene/TransformerTest.java
> Transformer

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/mang0r/EncodingSelector.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/mang0r/EncodingSelectorTest.java
> implementation done

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/leirth/FileReaderWriter.java
> Feature for FileReaderWriter

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/leirth/EncodingSelector.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/leirth/EncodingSelectorTest.java
> Feature for encoding selector

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/ryadbouzourene/EncodingSelector.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/ryadbouzourene/EncodingSelectorTest.java
> encoding passing test

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/axelrochat/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/axelrochat/TransformerTest.java
Closes #324 
Note : le dernier test fail pour une raison que j'ignore, je l'ai donc laissé en Disabled. Je ferai une autre pull request si je trouve le problème
> Transformer Axel Rochat

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/elchami21/FileReaderWriter.java
> FileReadWrite

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/aleddaheig/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/aleddaheig/TransformerTest.java
PR #423 This pr only cover the transformer feature
> Transformer for aleddaheig

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/FehlmannDy/EncodingSelector.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/FehlmannDy/EncodingSelectorTest.java
> EncodingSelector for FehlmannDy

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/FehlmannDy/FileExplorer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/FehlmannDy/FileExplorerTests.java
> FileExplorer for FehlmannDy

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/Romain720/EncodingSelector.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/Romain720/EncodingSelectorTest.java
> EncodingSelector for Romain720

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/Romain720/FileReaderWriter.java
> FileReaderWriter for Romain720

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/FehlmannDy/FileReaderWriter.java
> FileReaderWriter for FehlmannDy

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/bvernet/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/bvernet/TransformerTest.java
> implements Transformer class

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/FehlmannDy/Transformer.java
- fileioapp/src/test/java/ch/heig/dai/lab/fileio/FehlmannDy/TransformerTest.java
> Transformer for FehlmannDy

- fileioapp/src/main/java/ch/heig/dai/lab/fileio/IlianTopalov/Transformer.java
> Implemented Transformer
